////////////////////////////////////////////////////////
// This file is generated by Zeenerator.
////////////////////////////////////////////////////////
#include "ZeeNet/Private/Convert/Authentication.h" 
#include "ZeeNet/Private/Convert/Data/DataAccount.h" 
#include "ZeeNet/Private/Convert/Data/DataCharacter.h" 

void Zee::Net::Message::Convert::FromTo(const Zee::Proto::Authentication::Login& InFrom, FZeeNetAuthenticationLogin& OutTo)
{
	OutTo.RC = To<EZeeNetAuthenticationReturnCode>(InFrom.rc()); 
	FromTo(InFrom.account(), OutTo.Account); 
	OutTo.Characters.Reserve(InFrom.characters().size());
	for (const auto& Elem : InFrom.characters()) { FromTo(Elem, OutTo.Characters.AddZeroed_GetRef()); }
}

void Zee::Net::Message::Convert::FromTo(const FZeeNetAuthenticationLogin& InFrom, Zee::Proto::Authentication::Login& OutTo)
{
	OutTo.set_rc(To<Zee::Proto::Authentication::ReturnCode>(InFrom.RC)); 
	FromTo(InFrom.Account, *OutTo.mutable_account());
	OutTo.mutable_characters()->Reserve(InFrom.Characters.Num());
	for (const auto& Elem : InFrom.Characters) { FromTo(Elem, *OutTo.mutable_characters()->Add()); }
}

void Zee::Net::Message::Convert::FromTo(const Zee::Proto::Authentication::Logout& InFrom, FZeeNetAuthenticationLogout& OutTo)
{
	OutTo.RC = To<EZeeNetAuthenticationReturnCode>(InFrom.rc()); 
	OutTo.Id = To<FString>(InFrom.id()); 
	OutTo.UID = To<int64>(InFrom.uid()); 
}

void Zee::Net::Message::Convert::FromTo(const FZeeNetAuthenticationLogout& InFrom, Zee::Proto::Authentication::Logout& OutTo)
{
	OutTo.set_rc(To<Zee::Proto::Authentication::ReturnCode>(InFrom.RC)); 
	OutTo.set_id(To<std::string>(InFrom.Id)); 
	OutTo.set_uid(To<int64>(InFrom.UID)); 
}

