////////////////////////////////////////////////////////
// This file is generated by Zeenerator.
////////////////////////////////////////////////////////
#include "ZeeNet/Private/Convert/Collection.h" 

void Zee::Net::Message::Convert::FromTo(const Zee::Proto::Collection::Collect& InFrom, FZeeNetCollectionCollect& OutTo)
{
	OutTo.RC = To<EZeeNetCollectionReturnCode>(InFrom.rc()); 
	OutTo.Id = To<int32>(InFrom.id()); 
}

void Zee::Net::Message::Convert::FromTo(const FZeeNetCollectionCollect& InFrom, Zee::Proto::Collection::Collect& OutTo)
{
	OutTo.set_rc(To<Zee::Proto::Collection::ReturnCode>(InFrom.RC)); 
	OutTo.set_id(To<int32>(InFrom.Id)); 
}

void Zee::Net::Message::Convert::FromTo(const Zee::Proto::Collection::Get& InFrom, FZeeNetCollectionGet& OutTo)
{
	OutTo.Ids.Reserve(InFrom.ids().size());
	for (const auto& Elem : InFrom.ids()) { FromTo(Elem, OutTo.Ids.AddZeroed_GetRef()); }
}

void Zee::Net::Message::Convert::FromTo(const FZeeNetCollectionGet& InFrom, Zee::Proto::Collection::Get& OutTo)
{
	OutTo.mutable_ids()->Reserve(InFrom.Ids.Num());
	for (const auto& Elem : InFrom.Ids) { FromTo(Elem, *OutTo.mutable_ids()->Add()); }
}

