////////////////////////////////////////////////////////
// This file is generated by Zeenerator.
////////////////////////////////////////////////////////
#pragma once 
#include "CoreMinimal.h" 
#include "ZeeNet/Public/Messages/Packet.h" 
#include "ZeeNet/Private/Messages/Packet.pb.h" 
#include "ZeeNet/Private/ZeeNetMessageConvert.h" 

namespace Zee::Net::Message::Convert 
{ 
	template<> struct TZeeNetMapping_ProtoToPoint<Zee::Proto::Packet::Header> { static constexpr int32 Point = 0x3001; }; 
	template<> struct TZeeNetMapping_PointToProto<TZeeNetMapping_ProtoToPoint<Zee::Proto::Packet::Header>::Point> { using Type = Zee::Proto::Packet::Header; }; 
	FORCEINLINE void FromTo(const Zee::Proto::Packet::Header& InFrom, FZeeNetPacketHeader& OutTo);
	FORCEINLINE void FromTo(const FZeeNetPacketHeader& InFrom, Zee::Proto::Packet::Header& OutTo);

} 
