////////////////////////////////////////////////////////
// This file is generated by Zeenerator.
////////////////////////////////////////////////////////
#pragma once
#include "ZeeNet.h"
#include "ZeeNet/Public/Messages/Chat.h"
#include "ZeeNet/Public/Interface/Handler/ZeeNetNotifyHandler.h"

struct ZEENET_API IZeeNetNotifyHandler_Chat 
	: public IZeeNetNotifyHandler 
{
	const TCHAR* GetHandlerName() const final { return TEXT("Notify_Chat"); } 

	virtual void OnNotify(const FZeeNetChatSpeak& InMessage) { UE_LOG(LogZeeNet, Warning, TEXT("OnNotify is not impl: 'FZeeNetChatSpeak'")); } 
	virtual void OnNotify(const FZeeNetChatSpeak1& InMessage) { UE_LOG(LogZeeNet, Warning, TEXT("OnNotify is not impl: 'FZeeNetChatSpeak1'")); } 
};


