////////////////////////////////////////////////////////
// This file is generated by Zeenerator.
////////////////////////////////////////////////////////
#pragma once
#include "ZeeNet.h"
#include "ZeeNet/Public/Messages/Dedicate.h"
#include "ZeeNet/Public/Interface/Handler/ZeeNetNotifyHandler.h"

struct ZEENET_API IZeeNetNotifyHandler_Dedicate 
	: public IZeeNetNotifyHandler 
{
	const FString& GetHandlerName() const final { static FString Name = TEXT("Notify_Dedicate"); return Name; } 

	virtual void OnNotify(const FZeeNetDedicateLogin& InMessage) { UE_LOG(LogZeeNet, Warning, TEXT("OnNotify is not impl: 'FZeeNetDedicateLogin'")); } 
	virtual void OnNotify(const FZeeNetDedicateMove& InMessage) { UE_LOG(LogZeeNet, Warning, TEXT("OnNotify is not impl: 'FZeeNetDedicateMove'")); } 
	virtual void OnNotify(const FZeeNetDedicateLeave& InMessage) { UE_LOG(LogZeeNet, Warning, TEXT("OnNotify is not impl: 'FZeeNetDedicateLeave'")); } 
};

