////////////////////////////////////////////////////////
// This file is generated by Zeenerator.
////////////////////////////////////////////////////////
#pragma once
#include "ZeeNet.h"
#include "ZeeNet/Public/Messages/Test.h"
#include "ZeeNet/Public/Interface/Handler/ZeeNetNotifyHandler.h"

struct ZEENET_API IZeeNetNotifyHandler_Test 
	: public IZeeNetNotifyHandler 
{
	const TCHAR* GetHandlerName() const final { return TEXT("Notify_Test"); } 

	virtual void OnNotify(const FZeeNetTestMessage& InMessage) { UE_LOG(LogZeeNet, Warning, TEXT("OnNotify is not impl: 'FZeeNetTestMessage'")); } 
};


