////////////////////////////////////////////////////////
// This file is generated by Zeenerator.
////////////////////////////////////////////////////////
#include "ZeeNetClient.h"
#include "ZeeNet/Public/Messages/Packet.h"
#include "ZeeNet/Private/ZeeNetMessageSerializerDef.h"
#include "ZeeNet/Private/Handler/NotifyDef.h"
#include "ZeeNet/Public/Interface/Handler/Notify/UserCharacter.h" 

FZeeNetNotifyHandlerArray* FindNotifyHandler_UserCharacter(int32 Point, TMap<FString, FZeeNetNotifyHandlerArray>& NotifyHandlers) { 
	switch (Point) { 
	case TZeeNetPacketTraits<FZeeNetUserCharacterCreate>::Point: [[fallthrough]]; 
	case TZeeNetPacketTraits<FZeeNetUserCharacterGet>::Point: 
		return NotifyHandlers.Find(TEXT("Notify_UserCharacter")); 
	default: break; 
	}

	return nullptr; 
}

bool ConsumeNotifyMessage_UserCharacter(TSharedPtr<struct FZeeNetPacketSerializerBase> Packet, FZeeNetNotifyHandlerArray& NotifyHandlers) { 
	const int32 PacketPoint = Packet->GetHeader().Point; 
	switch (PacketPoint) { 
		ZEENET_CASE_CONSUME_NOTIFY(UserCharacter, Create);
		ZEENET_CASE_CONSUME_NOTIFY(UserCharacter, Get);
	default: break; 
	} 

	return false; 
}

