////////////////////////////////////////////////////////
// This file is generated by Zeenerator.
////////////////////////////////////////////////////////
#include "ZeeNetClient.h"
#include "ZeeNet/Public/Messages/Packet.h"
#include "ZeeNet/Private/ZeeNetMessageSerializerDef.h"
#include "ZeeNet/Private/Handler/NotifyDef.h"
#include "ZeeNet/Public/Interface/Handler/Notify/Authentication.h" 

FZeeNetNotifyHandlerArray* FindNotifyHandler_Authentication(int32 Point, TMap<FString, FZeeNetNotifyHandlerArray>& NotifyHandlers) { 
	switch (Point) { 
	case TZeeNetPacketTraits<FZeeNetAuthenticationLogin>::Point: [[fallthrough]]; 
	case TZeeNetPacketTraits<FZeeNetAuthenticationLogout>::Point: 
		return NotifyHandlers.Find(TEXT("Notify_Authentication")); 
	default: break; 
	}

	return nullptr; 
}

bool ConsumeNotifyMessage_Authentication(TSharedPtr<struct FZeeNetPacketSerializerBase> Packet, FZeeNetNotifyHandlerArray& NotifyHandlers) { 
	const int32 PacketPoint = Packet->GetHeader().Point; 
	switch (PacketPoint) { 
		ZEENET_CASE_CONSUME_NOTIFY(Authentication, Login);
		ZEENET_CASE_CONSUME_NOTIFY(Authentication, Logout);
	default: break; 
	} 

	return false; 
}

