////////////////////////////////////////////////////////
// This file is generated by Zeenerator.
////////////////////////////////////////////////////////
#pragma once
#include "ZeeNet.h"
#include "ZeeNet/Public/Messages/Chat.h"
#include "ZeeNet/Public/Interface/Handler/ZeeNetRequestHandler.h"

struct ZEENET_API IZeeNetRequestHandler_Chat 
	: public IZeeNetRequestHandler 
{
	const FString& GetHandlerName() const final { static FString Name = TEXT("Request_Chat"); return Name; } 

	[[nodiscard]] virtual EZeeNetRequestHandlerResponse OnRequest(const TSharedPtr<IZeeNetResponser>& InResponser, const FZeeNetChatSpeak& InMessage) { 
		return EZeeNetRequestHandlerResponse::NoResponse; 
	}

	[[nodiscard]] virtual EZeeNetRequestHandlerResponse OnRequest(const TSharedPtr<IZeeNetResponser>& InResponser, const FZeeNetChatSpeak1& InMessage) { 
		return EZeeNetRequestHandlerResponse::NoResponse; 
	}

};

