
using System.Text;

namespace Zee
{
    static public partial class Generator
    {
        static public readonly string DescriptionGenerated = 
@"////////////////////////////////////////////////////////
// This file is generated by Zeenerator.
////////////////////////////////////////////////////////
";
    }
}
