////////////////////////////////////////////////////////
// This file is generated by Zeenerator.
////////////////////////////////////////////////////////
#include "ZeeNetClient.h"
#include "ZeeNet/Private/ZeeNetMessageSerializerDef.h"
#include "ZeeNet/Private/Handler/RequestDef.h"

#include "ZeeNet/Public/Interface/Handler/Request/Test2.h" 
#include "ZeeNet/Public/Interface/Handler/Request/Test2.h" 

FZeeNetRequestHandlerArray* FindRequestHandler_Test2(int32 Point, TMap<FString, FZeeNetRequestHandlerArray>& RequestHandlers) { 
	switch (Point) { 
	case TZeeNetMapping_UnrealToPoint<FZeeNetTest2TestMessage5>::Point: [[fallthrough]]; 
	case TZeeNetMapping_UnrealToPoint<FZeeNetTest2TestMessage3>::Point: [[fallthrough]]; 
	case TZeeNetMapping_UnrealToPoint<FZeeNetTest2TestMessage4>::Point: [[fallthrough]]; 
	case TZeeNetMapping_UnrealToPoint<FZeeNetTest2TestMessage2>::Point: 
		return RequestHandlers.Find(TEXT("Request_Test2")); 
	default: break; 
	}

	return nullptr; 
}

EZeeNetRequestHandlerResponse ConsumeRequestMessage_Test2(TSharedPtr<IZeeNetResponser> Responser
	, TSharedPtr<struct FZeeNetPacketSerializerBase> Packet
	, FZeeNetRequestHandlerArray& RequestHandlers) { 
	const int32 PacketPoint = Packet->GetHeader().Point; 
	switch (PacketPoint) { 
		ZEENET_CASE_CONSUME_REQUEST(Test2, TestMessage5);
		ZEENET_CASE_CONSUME_REQUEST(Test2, TestMessage3);
		ZEENET_CASE_CONSUME_REQUEST(Test2, TestMessage4);
		ZEENET_CASE_CONSUME_REQUEST(Test2, TestMessage2);
	default: break; 
	} 

	return EZeeNetRequestHandlerResponse::NoResponse; 
}

