// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: Depth1/Depth2/test3.proto
// Protobuf C++ Version: 5.27.0

#include "Depth1/Depth2/test3.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace P1 {

inline constexpr Depth2Test3::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : sss_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR Depth2Test3::Depth2Test3(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct Depth2Test3DefaultTypeInternal {
  PROTOBUF_CONSTEXPR Depth2Test3DefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~Depth2Test3DefaultTypeInternal() {}
  union {
    Depth2Test3 _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 Depth2Test3DefaultTypeInternal _Depth2Test3_default_instance_;
}  // namespace P1
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_Depth1_2fDepth2_2ftest3_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_Depth1_2fDepth2_2ftest3_2eproto = nullptr;
const ::uint32_t
    TableStruct_Depth1_2fDepth2_2ftest3_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::P1::Depth2Test3, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::P1::Depth2Test3, _impl_.sss_),
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::P1::Depth2Test3)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::P1::_Depth2Test3_default_instance_._instance,
};
const char descriptor_table_protodef_Depth1_2fDepth2_2ftest3_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\031Depth1/Depth2/test3.proto\022\002P1\"\032\n\013Depth"
    "2Test3\022\013\n\003SSS\030\001 \001(\tb\006proto3"
};
static ::absl::once_flag descriptor_table_Depth1_2fDepth2_2ftest3_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_Depth1_2fDepth2_2ftest3_2eproto = {
    false,
    false,
    67,
    descriptor_table_protodef_Depth1_2fDepth2_2ftest3_2eproto,
    "Depth1/Depth2/test3.proto",
    &descriptor_table_Depth1_2fDepth2_2ftest3_2eproto_once,
    nullptr,
    0,
    1,
    schemas,
    file_default_instances,
    TableStruct_Depth1_2fDepth2_2ftest3_2eproto::offsets,
    file_level_enum_descriptors_Depth1_2fDepth2_2ftest3_2eproto,
    file_level_service_descriptors_Depth1_2fDepth2_2ftest3_2eproto,
};
namespace P1 {
// ===================================================================

class Depth2Test3::_Internal {
 public:
};

Depth2Test3::Depth2Test3(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:P1.Depth2Test3)
}
inline PROTOBUF_NDEBUG_INLINE Depth2Test3::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::P1::Depth2Test3& from_msg)
      : sss_(arena, from.sss_),
        _cached_size_{0} {}

Depth2Test3::Depth2Test3(
    ::google::protobuf::Arena* arena,
    const Depth2Test3& from)
    : ::google::protobuf::Message(arena) {
  Depth2Test3* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:P1.Depth2Test3)
}
inline PROTOBUF_NDEBUG_INLINE Depth2Test3::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : sss_(arena),
        _cached_size_{0} {}

inline void Depth2Test3::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
Depth2Test3::~Depth2Test3() {
  // @@protoc_insertion_point(destructor:P1.Depth2Test3)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void Depth2Test3::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.sss_.Destroy();
  _impl_.~Impl_();
}

const ::google::protobuf::MessageLite::ClassData*
Depth2Test3::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::
      ClassDataFull _data_ = {
          {
              &_table_.header,
              nullptr,  // OnDemandRegisterArenaDtor
              nullptr,  // IsInitialized
              PROTOBUF_FIELD_OFFSET(Depth2Test3, _impl_._cached_size_),
              false,
          },
          &Depth2Test3::MergeImpl,
          &Depth2Test3::kDescriptorMethods,
          &descriptor_table_Depth1_2fDepth2_2ftest3_2eproto,
          nullptr,  // tracker
      };
  ::google::protobuf::internal::PrefetchToLocalCache(&_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_data_.tc_table);
  return _data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 26, 2> Depth2Test3::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_Depth2Test3_default_instance_._instance,
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::P1::Depth2Test3>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string SSS = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(Depth2Test3, _impl_.sss_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string SSS = 1;
    {PROTOBUF_FIELD_OFFSET(Depth2Test3, _impl_.sss_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\16\3\0\0\0\0\0\0"
    "P1.Depth2Test3"
    "SSS"
  }},
};

PROTOBUF_NOINLINE void Depth2Test3::Clear() {
// @@protoc_insertion_point(message_clear_start:P1.Depth2Test3)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.sss_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

::uint8_t* Depth2Test3::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:P1.Depth2Test3)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // string SSS = 1;
  if (!this->_internal_sss().empty()) {
    const std::string& _s = this->_internal_sss();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "P1.Depth2Test3.SSS");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:P1.Depth2Test3)
  return target;
}

::size_t Depth2Test3::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:P1.Depth2Test3)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string SSS = 1;
  if (!this->_internal_sss().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_sss());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}


void Depth2Test3::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<Depth2Test3*>(&to_msg);
  auto& from = static_cast<const Depth2Test3&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:P1.Depth2Test3)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_sss().empty()) {
    _this->_internal_set_sss(from._internal_sss());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void Depth2Test3::CopyFrom(const Depth2Test3& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:P1.Depth2Test3)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void Depth2Test3::InternalSwap(Depth2Test3* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.sss_, &other->_impl_.sss_, arena);
}

::google::protobuf::Metadata Depth2Test3::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace P1
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_Depth1_2fDepth2_2ftest3_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
