// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: Depth1/Depth2/test3.proto
// Protobuf C++ Version: 5.27.0

#ifndef GOOGLE_PROTOBUF_INCLUDED_Depth1_2fDepth2_2ftest3_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_Depth1_2fDepth2_2ftest3_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5027000
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_Depth1_2fDepth2_2ftest3_2eproto

namespace google {
namespace protobuf {
namespace internal {
class AnyMetadata;
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_Depth1_2fDepth2_2ftest3_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_Depth1_2fDepth2_2ftest3_2eproto;
namespace P1 {
class Depth2Test3;
struct Depth2Test3DefaultTypeInternal;
extern Depth2Test3DefaultTypeInternal _Depth2Test3_default_instance_;
}  // namespace P1
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace P1 {

// ===================================================================


// -------------------------------------------------------------------

class Depth2Test3 final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:P1.Depth2Test3) */ {
 public:
  inline Depth2Test3() : Depth2Test3(nullptr) {}
  ~Depth2Test3() override;
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR Depth2Test3(
      ::google::protobuf::internal::ConstantInitialized);

  inline Depth2Test3(const Depth2Test3& from) : Depth2Test3(nullptr, from) {}
  inline Depth2Test3(Depth2Test3&& from) noexcept
      : Depth2Test3(nullptr, std::move(from)) {}
  inline Depth2Test3& operator=(const Depth2Test3& from) {
    CopyFrom(from);
    return *this;
  }
  inline Depth2Test3& operator=(Depth2Test3&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Depth2Test3& default_instance() {
    return *internal_default_instance();
  }
  static inline const Depth2Test3* internal_default_instance() {
    return reinterpret_cast<const Depth2Test3*>(
        &_Depth2Test3_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(Depth2Test3& a, Depth2Test3& b) { a.Swap(&b); }
  inline void Swap(Depth2Test3* other) {
    if (other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr && GetArena() == other->GetArena()) {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Depth2Test3* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Depth2Test3* New(::google::protobuf::Arena* arena = nullptr) const final {
    return ::google::protobuf::Message::DefaultConstruct<Depth2Test3>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const Depth2Test3& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const Depth2Test3& from) { Depth2Test3::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() final;
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(Depth2Test3* other);
 private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() { return "P1.Depth2Test3"; }

 protected:
  explicit Depth2Test3(::google::protobuf::Arena* arena);
  Depth2Test3(::google::protobuf::Arena* arena, const Depth2Test3& from);
  Depth2Test3(::google::protobuf::Arena* arena, Depth2Test3&& from) noexcept
      : Depth2Test3(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::Message::ClassData* GetClassData() const final;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kSSSFieldNumber = 1,
  };
  // string SSS = 1;
  void clear_sss() ;
  const std::string& sss() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_sss(Arg_&& arg, Args_... args);
  std::string* mutable_sss();
  PROTOBUF_NODISCARD std::string* release_sss();
  void set_allocated_sss(std::string* value);

  private:
  const std::string& _internal_sss() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_sss(
      const std::string& value);
  std::string* _internal_mutable_sss();

  public:
  // @@protoc_insertion_point(class_scope:P1.Depth2Test3)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      0, 1, 0,
      26, 2>
      _table_;

  static constexpr const void* _raw_default_instance_ =
      &_Depth2Test3_default_instance_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const Depth2Test3& from_msg);
    ::google::protobuf::internal::ArenaStringPtr sss_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Depth1_2fDepth2_2ftest3_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// Depth2Test3

// string SSS = 1;
inline void Depth2Test3::clear_sss() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.sss_.ClearToEmpty();
}
inline const std::string& Depth2Test3::sss() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:P1.Depth2Test3.SSS)
  return _internal_sss();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void Depth2Test3::set_sss(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.sss_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:P1.Depth2Test3.SSS)
}
inline std::string* Depth2Test3::mutable_sss() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_sss();
  // @@protoc_insertion_point(field_mutable:P1.Depth2Test3.SSS)
  return _s;
}
inline const std::string& Depth2Test3::_internal_sss() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.sss_.Get();
}
inline void Depth2Test3::_internal_set_sss(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.sss_.Set(value, GetArena());
}
inline std::string* Depth2Test3::_internal_mutable_sss() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.sss_.Mutable( GetArena());
}
inline std::string* Depth2Test3::release_sss() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:P1.Depth2Test3.SSS)
  return _impl_.sss_.Release();
}
inline void Depth2Test3::set_allocated_sss(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.sss_.SetAllocated(value, GetArena());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.sss_.IsDefault()) {
          _impl_.sss_.Set("", GetArena());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:P1.Depth2Test3.SSS)
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace P1


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_Depth1_2fDepth2_2ftest3_2eproto_2epb_2eh
