// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Dedicate.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_Dedicate_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_Dedicate_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3018000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3018000 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
#include "Data/DataDedicate.pb.h"
#include "Data/DataCharacter.pb.h"
#include "Data/DataCommon.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_Dedicate_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_Dedicate_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[3]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_Dedicate_2eproto;
namespace Zee {
namespace Proto {
namespace Dedicate {
class Leave;
struct LeaveDefaultTypeInternal;
extern LeaveDefaultTypeInternal _Leave_default_instance_;
class Login;
struct LoginDefaultTypeInternal;
extern LoginDefaultTypeInternal _Login_default_instance_;
class Move;
struct MoveDefaultTypeInternal;
extern MoveDefaultTypeInternal _Move_default_instance_;
}  // namespace Dedicate
}  // namespace Proto
}  // namespace Zee
PROTOBUF_NAMESPACE_OPEN
template<> ::Zee::Proto::Dedicate::Leave* Arena::CreateMaybeMessage<::Zee::Proto::Dedicate::Leave>(Arena*);
template<> ::Zee::Proto::Dedicate::Login* Arena::CreateMaybeMessage<::Zee::Proto::Dedicate::Login>(Arena*);
template<> ::Zee::Proto::Dedicate::Move* Arena::CreateMaybeMessage<::Zee::Proto::Dedicate::Move>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace Zee {
namespace Proto {
namespace Dedicate {

enum ReturnCode : int {
  RC_SUCCESS = 0,
  RC_FAILED_UNKNOWN = 1,
  RC_FAILED_DEDI_NOT_FOUND = 2,
  ReturnCode_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::min(),
  ReturnCode_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::max()
};
bool ReturnCode_IsValid(int value);
constexpr ReturnCode ReturnCode_MIN = RC_SUCCESS;
constexpr ReturnCode ReturnCode_MAX = RC_FAILED_DEDI_NOT_FOUND;
constexpr int ReturnCode_ARRAYSIZE = ReturnCode_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* ReturnCode_descriptor();
template<typename T>
inline const std::string& ReturnCode_Name(T enum_t_value) {
  static_assert(::std::is_same<T, ReturnCode>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function ReturnCode_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    ReturnCode_descriptor(), enum_t_value);
}
inline bool ReturnCode_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, ReturnCode* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<ReturnCode>(
    ReturnCode_descriptor(), name, value);
}
// ===================================================================

class Login final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Zee.Proto.Dedicate.Login) */ {
 public:
  inline Login() : Login(nullptr) {}
  ~Login() override;
  explicit constexpr Login(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Login(const Login& from);
  Login(Login&& from) noexcept
    : Login() {
    *this = ::std::move(from);
  }

  inline Login& operator=(const Login& from) {
    CopyFrom(from);
    return *this;
  }
  inline Login& operator=(Login&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Login& default_instance() {
    return *internal_default_instance();
  }
  static inline const Login* internal_default_instance() {
    return reinterpret_cast<const Login*>(
               &_Login_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Login& a, Login& b) {
    a.Swap(&b);
  }
  inline void Swap(Login* other) {
    if (other == this) return;
    if (GetOwningArena() == other->GetOwningArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Login* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Login* New() const final {
    return new Login();
  }

  Login* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Login>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Login& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const Login& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Login* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Zee.Proto.Dedicate.Login";
  }
  protected:
  explicit Login(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kDedicateServerFieldNumber = 2,
    kRCFieldNumber = 1,
  };
  // .Zee.Proto.Data.DedicateServer DedicateServer = 2;
  bool has_dedicateserver() const;
  private:
  bool _internal_has_dedicateserver() const;
  public:
  void clear_dedicateserver();
  const ::Zee::Proto::Data::DedicateServer& dedicateserver() const;
  PROTOBUF_MUST_USE_RESULT ::Zee::Proto::Data::DedicateServer* release_dedicateserver();
  ::Zee::Proto::Data::DedicateServer* mutable_dedicateserver();
  void set_allocated_dedicateserver(::Zee::Proto::Data::DedicateServer* dedicateserver);
  private:
  const ::Zee::Proto::Data::DedicateServer& _internal_dedicateserver() const;
  ::Zee::Proto::Data::DedicateServer* _internal_mutable_dedicateserver();
  public:
  void unsafe_arena_set_allocated_dedicateserver(
      ::Zee::Proto::Data::DedicateServer* dedicateserver);
  ::Zee::Proto::Data::DedicateServer* unsafe_arena_release_dedicateserver();

  // .Zee.Proto.Dedicate.ReturnCode RC = 1;
  void clear_rc();
  ::Zee::Proto::Dedicate::ReturnCode rc() const;
  void set_rc(::Zee::Proto::Dedicate::ReturnCode value);
  private:
  ::Zee::Proto::Dedicate::ReturnCode _internal_rc() const;
  void _internal_set_rc(::Zee::Proto::Dedicate::ReturnCode value);
  public:

  // @@protoc_insertion_point(class_scope:Zee.Proto.Dedicate.Login)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::Zee::Proto::Data::DedicateServer* dedicateserver_;
  int rc_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_Dedicate_2eproto;
};
// -------------------------------------------------------------------

class Move final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Zee.Proto.Dedicate.Move) */ {
 public:
  inline Move() : Move(nullptr) {}
  ~Move() override;
  explicit constexpr Move(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Move(const Move& from);
  Move(Move&& from) noexcept
    : Move() {
    *this = ::std::move(from);
  }

  inline Move& operator=(const Move& from) {
    CopyFrom(from);
    return *this;
  }
  inline Move& operator=(Move&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Move& default_instance() {
    return *internal_default_instance();
  }
  static inline const Move* internal_default_instance() {
    return reinterpret_cast<const Move*>(
               &_Move_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(Move& a, Move& b) {
    a.Swap(&b);
  }
  inline void Swap(Move* other) {
    if (other == this) return;
    if (GetOwningArena() == other->GetOwningArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Move* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Move* New() const final {
    return new Move();
  }

  Move* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Move>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Move& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const Move& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Move* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Zee.Proto.Dedicate.Move";
  }
  protected:
  explicit Move(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kUserIpFieldNumber = 5,
    kCharacterFieldNumber = 2,
    kToServerFieldNumber = 3,
    kPositionFieldNumber = 4,
    kRCFieldNumber = 1,
  };
  // string UserIp = 5;
  void clear_userip();
  const std::string& userip() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_userip(ArgT0&& arg0, ArgT... args);
  std::string* mutable_userip();
  PROTOBUF_MUST_USE_RESULT std::string* release_userip();
  void set_allocated_userip(std::string* userip);
  private:
  const std::string& _internal_userip() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_userip(const std::string& value);
  std::string* _internal_mutable_userip();
  public:

  // .Zee.Proto.Data.Character Character = 2;
  bool has_character() const;
  private:
  bool _internal_has_character() const;
  public:
  void clear_character();
  const ::Zee::Proto::Data::Character& character() const;
  PROTOBUF_MUST_USE_RESULT ::Zee::Proto::Data::Character* release_character();
  ::Zee::Proto::Data::Character* mutable_character();
  void set_allocated_character(::Zee::Proto::Data::Character* character);
  private:
  const ::Zee::Proto::Data::Character& _internal_character() const;
  ::Zee::Proto::Data::Character* _internal_mutable_character();
  public:
  void unsafe_arena_set_allocated_character(
      ::Zee::Proto::Data::Character* character);
  ::Zee::Proto::Data::Character* unsafe_arena_release_character();

  // .Zee.Proto.Data.DedicateServer ToServer = 3;
  bool has_toserver() const;
  private:
  bool _internal_has_toserver() const;
  public:
  void clear_toserver();
  const ::Zee::Proto::Data::DedicateServer& toserver() const;
  PROTOBUF_MUST_USE_RESULT ::Zee::Proto::Data::DedicateServer* release_toserver();
  ::Zee::Proto::Data::DedicateServer* mutable_toserver();
  void set_allocated_toserver(::Zee::Proto::Data::DedicateServer* toserver);
  private:
  const ::Zee::Proto::Data::DedicateServer& _internal_toserver() const;
  ::Zee::Proto::Data::DedicateServer* _internal_mutable_toserver();
  public:
  void unsafe_arena_set_allocated_toserver(
      ::Zee::Proto::Data::DedicateServer* toserver);
  ::Zee::Proto::Data::DedicateServer* unsafe_arena_release_toserver();

  // .Zee.Proto.Data.Position Position = 4;
  bool has_position() const;
  private:
  bool _internal_has_position() const;
  public:
  void clear_position();
  const ::Zee::Proto::Data::Position& position() const;
  PROTOBUF_MUST_USE_RESULT ::Zee::Proto::Data::Position* release_position();
  ::Zee::Proto::Data::Position* mutable_position();
  void set_allocated_position(::Zee::Proto::Data::Position* position);
  private:
  const ::Zee::Proto::Data::Position& _internal_position() const;
  ::Zee::Proto::Data::Position* _internal_mutable_position();
  public:
  void unsafe_arena_set_allocated_position(
      ::Zee::Proto::Data::Position* position);
  ::Zee::Proto::Data::Position* unsafe_arena_release_position();

  // .Zee.Proto.Dedicate.ReturnCode RC = 1;
  void clear_rc();
  ::Zee::Proto::Dedicate::ReturnCode rc() const;
  void set_rc(::Zee::Proto::Dedicate::ReturnCode value);
  private:
  ::Zee::Proto::Dedicate::ReturnCode _internal_rc() const;
  void _internal_set_rc(::Zee::Proto::Dedicate::ReturnCode value);
  public:

  // @@protoc_insertion_point(class_scope:Zee.Proto.Dedicate.Move)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr userip_;
  ::Zee::Proto::Data::Character* character_;
  ::Zee::Proto::Data::DedicateServer* toserver_;
  ::Zee::Proto::Data::Position* position_;
  int rc_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_Dedicate_2eproto;
};
// -------------------------------------------------------------------

class Leave final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Zee.Proto.Dedicate.Leave) */ {
 public:
  inline Leave() : Leave(nullptr) {}
  ~Leave() override;
  explicit constexpr Leave(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Leave(const Leave& from);
  Leave(Leave&& from) noexcept
    : Leave() {
    *this = ::std::move(from);
  }

  inline Leave& operator=(const Leave& from) {
    CopyFrom(from);
    return *this;
  }
  inline Leave& operator=(Leave&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Leave& default_instance() {
    return *internal_default_instance();
  }
  static inline const Leave* internal_default_instance() {
    return reinterpret_cast<const Leave*>(
               &_Leave_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(Leave& a, Leave& b) {
    a.Swap(&b);
  }
  inline void Swap(Leave* other) {
    if (other == this) return;
    if (GetOwningArena() == other->GetOwningArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Leave* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Leave* New() const final {
    return new Leave();
  }

  Leave* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Leave>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Leave& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const Leave& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Leave* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Zee.Proto.Dedicate.Leave";
  }
  protected:
  explicit Leave(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kCharacterFieldNumber = 1,
    kPositionFieldNumber = 2,
  };
  // .Zee.Proto.Data.Character Character = 1;
  bool has_character() const;
  private:
  bool _internal_has_character() const;
  public:
  void clear_character();
  const ::Zee::Proto::Data::Character& character() const;
  PROTOBUF_MUST_USE_RESULT ::Zee::Proto::Data::Character* release_character();
  ::Zee::Proto::Data::Character* mutable_character();
  void set_allocated_character(::Zee::Proto::Data::Character* character);
  private:
  const ::Zee::Proto::Data::Character& _internal_character() const;
  ::Zee::Proto::Data::Character* _internal_mutable_character();
  public:
  void unsafe_arena_set_allocated_character(
      ::Zee::Proto::Data::Character* character);
  ::Zee::Proto::Data::Character* unsafe_arena_release_character();

  // .Zee.Proto.Data.Position Position = 2;
  bool has_position() const;
  private:
  bool _internal_has_position() const;
  public:
  void clear_position();
  const ::Zee::Proto::Data::Position& position() const;
  PROTOBUF_MUST_USE_RESULT ::Zee::Proto::Data::Position* release_position();
  ::Zee::Proto::Data::Position* mutable_position();
  void set_allocated_position(::Zee::Proto::Data::Position* position);
  private:
  const ::Zee::Proto::Data::Position& _internal_position() const;
  ::Zee::Proto::Data::Position* _internal_mutable_position();
  public:
  void unsafe_arena_set_allocated_position(
      ::Zee::Proto::Data::Position* position);
  ::Zee::Proto::Data::Position* unsafe_arena_release_position();

  // @@protoc_insertion_point(class_scope:Zee.Proto.Dedicate.Leave)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::Zee::Proto::Data::Character* character_;
  ::Zee::Proto::Data::Position* position_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_Dedicate_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Login

// .Zee.Proto.Dedicate.ReturnCode RC = 1;
inline void Login::clear_rc() {
  rc_ = 0;
}
inline ::Zee::Proto::Dedicate::ReturnCode Login::_internal_rc() const {
  return static_cast< ::Zee::Proto::Dedicate::ReturnCode >(rc_);
}
inline ::Zee::Proto::Dedicate::ReturnCode Login::rc() const {
  // @@protoc_insertion_point(field_get:Zee.Proto.Dedicate.Login.RC)
  return _internal_rc();
}
inline void Login::_internal_set_rc(::Zee::Proto::Dedicate::ReturnCode value) {
  
  rc_ = value;
}
inline void Login::set_rc(::Zee::Proto::Dedicate::ReturnCode value) {
  _internal_set_rc(value);
  // @@protoc_insertion_point(field_set:Zee.Proto.Dedicate.Login.RC)
}

// .Zee.Proto.Data.DedicateServer DedicateServer = 2;
inline bool Login::_internal_has_dedicateserver() const {
  return this != internal_default_instance() && dedicateserver_ != nullptr;
}
inline bool Login::has_dedicateserver() const {
  return _internal_has_dedicateserver();
}
inline const ::Zee::Proto::Data::DedicateServer& Login::_internal_dedicateserver() const {
  const ::Zee::Proto::Data::DedicateServer* p = dedicateserver_;
  return p != nullptr ? *p : reinterpret_cast<const ::Zee::Proto::Data::DedicateServer&>(
      ::Zee::Proto::Data::_DedicateServer_default_instance_);
}
inline const ::Zee::Proto::Data::DedicateServer& Login::dedicateserver() const {
  // @@protoc_insertion_point(field_get:Zee.Proto.Dedicate.Login.DedicateServer)
  return _internal_dedicateserver();
}
inline void Login::unsafe_arena_set_allocated_dedicateserver(
    ::Zee::Proto::Data::DedicateServer* dedicateserver) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(dedicateserver_);
  }
  dedicateserver_ = dedicateserver;
  if (dedicateserver) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:Zee.Proto.Dedicate.Login.DedicateServer)
}
inline ::Zee::Proto::Data::DedicateServer* Login::release_dedicateserver() {
  
  ::Zee::Proto::Data::DedicateServer* temp = dedicateserver_;
  dedicateserver_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::Zee::Proto::Data::DedicateServer* Login::unsafe_arena_release_dedicateserver() {
  // @@protoc_insertion_point(field_release:Zee.Proto.Dedicate.Login.DedicateServer)
  
  ::Zee::Proto::Data::DedicateServer* temp = dedicateserver_;
  dedicateserver_ = nullptr;
  return temp;
}
inline ::Zee::Proto::Data::DedicateServer* Login::_internal_mutable_dedicateserver() {
  
  if (dedicateserver_ == nullptr) {
    auto* p = CreateMaybeMessage<::Zee::Proto::Data::DedicateServer>(GetArenaForAllocation());
    dedicateserver_ = p;
  }
  return dedicateserver_;
}
inline ::Zee::Proto::Data::DedicateServer* Login::mutable_dedicateserver() {
  ::Zee::Proto::Data::DedicateServer* _msg = _internal_mutable_dedicateserver();
  // @@protoc_insertion_point(field_mutable:Zee.Proto.Dedicate.Login.DedicateServer)
  return _msg;
}
inline void Login::set_allocated_dedicateserver(::Zee::Proto::Data::DedicateServer* dedicateserver) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(dedicateserver_);
  }
  if (dedicateserver) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper<
            ::PROTOBUF_NAMESPACE_ID::MessageLite>::GetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(dedicateserver));
    if (message_arena != submessage_arena) {
      dedicateserver = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, dedicateserver, submessage_arena);
    }
    
  } else {
    
  }
  dedicateserver_ = dedicateserver;
  // @@protoc_insertion_point(field_set_allocated:Zee.Proto.Dedicate.Login.DedicateServer)
}

// -------------------------------------------------------------------

// Move

// .Zee.Proto.Dedicate.ReturnCode RC = 1;
inline void Move::clear_rc() {
  rc_ = 0;
}
inline ::Zee::Proto::Dedicate::ReturnCode Move::_internal_rc() const {
  return static_cast< ::Zee::Proto::Dedicate::ReturnCode >(rc_);
}
inline ::Zee::Proto::Dedicate::ReturnCode Move::rc() const {
  // @@protoc_insertion_point(field_get:Zee.Proto.Dedicate.Move.RC)
  return _internal_rc();
}
inline void Move::_internal_set_rc(::Zee::Proto::Dedicate::ReturnCode value) {
  
  rc_ = value;
}
inline void Move::set_rc(::Zee::Proto::Dedicate::ReturnCode value) {
  _internal_set_rc(value);
  // @@protoc_insertion_point(field_set:Zee.Proto.Dedicate.Move.RC)
}

// .Zee.Proto.Data.Character Character = 2;
inline bool Move::_internal_has_character() const {
  return this != internal_default_instance() && character_ != nullptr;
}
inline bool Move::has_character() const {
  return _internal_has_character();
}
inline const ::Zee::Proto::Data::Character& Move::_internal_character() const {
  const ::Zee::Proto::Data::Character* p = character_;
  return p != nullptr ? *p : reinterpret_cast<const ::Zee::Proto::Data::Character&>(
      ::Zee::Proto::Data::_Character_default_instance_);
}
inline const ::Zee::Proto::Data::Character& Move::character() const {
  // @@protoc_insertion_point(field_get:Zee.Proto.Dedicate.Move.Character)
  return _internal_character();
}
inline void Move::unsafe_arena_set_allocated_character(
    ::Zee::Proto::Data::Character* character) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(character_);
  }
  character_ = character;
  if (character) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:Zee.Proto.Dedicate.Move.Character)
}
inline ::Zee::Proto::Data::Character* Move::release_character() {
  
  ::Zee::Proto::Data::Character* temp = character_;
  character_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::Zee::Proto::Data::Character* Move::unsafe_arena_release_character() {
  // @@protoc_insertion_point(field_release:Zee.Proto.Dedicate.Move.Character)
  
  ::Zee::Proto::Data::Character* temp = character_;
  character_ = nullptr;
  return temp;
}
inline ::Zee::Proto::Data::Character* Move::_internal_mutable_character() {
  
  if (character_ == nullptr) {
    auto* p = CreateMaybeMessage<::Zee::Proto::Data::Character>(GetArenaForAllocation());
    character_ = p;
  }
  return character_;
}
inline ::Zee::Proto::Data::Character* Move::mutable_character() {
  ::Zee::Proto::Data::Character* _msg = _internal_mutable_character();
  // @@protoc_insertion_point(field_mutable:Zee.Proto.Dedicate.Move.Character)
  return _msg;
}
inline void Move::set_allocated_character(::Zee::Proto::Data::Character* character) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(character_);
  }
  if (character) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper<
            ::PROTOBUF_NAMESPACE_ID::MessageLite>::GetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(character));
    if (message_arena != submessage_arena) {
      character = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, character, submessage_arena);
    }
    
  } else {
    
  }
  character_ = character;
  // @@protoc_insertion_point(field_set_allocated:Zee.Proto.Dedicate.Move.Character)
}

// .Zee.Proto.Data.DedicateServer ToServer = 3;
inline bool Move::_internal_has_toserver() const {
  return this != internal_default_instance() && toserver_ != nullptr;
}
inline bool Move::has_toserver() const {
  return _internal_has_toserver();
}
inline const ::Zee::Proto::Data::DedicateServer& Move::_internal_toserver() const {
  const ::Zee::Proto::Data::DedicateServer* p = toserver_;
  return p != nullptr ? *p : reinterpret_cast<const ::Zee::Proto::Data::DedicateServer&>(
      ::Zee::Proto::Data::_DedicateServer_default_instance_);
}
inline const ::Zee::Proto::Data::DedicateServer& Move::toserver() const {
  // @@protoc_insertion_point(field_get:Zee.Proto.Dedicate.Move.ToServer)
  return _internal_toserver();
}
inline void Move::unsafe_arena_set_allocated_toserver(
    ::Zee::Proto::Data::DedicateServer* toserver) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(toserver_);
  }
  toserver_ = toserver;
  if (toserver) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:Zee.Proto.Dedicate.Move.ToServer)
}
inline ::Zee::Proto::Data::DedicateServer* Move::release_toserver() {
  
  ::Zee::Proto::Data::DedicateServer* temp = toserver_;
  toserver_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::Zee::Proto::Data::DedicateServer* Move::unsafe_arena_release_toserver() {
  // @@protoc_insertion_point(field_release:Zee.Proto.Dedicate.Move.ToServer)
  
  ::Zee::Proto::Data::DedicateServer* temp = toserver_;
  toserver_ = nullptr;
  return temp;
}
inline ::Zee::Proto::Data::DedicateServer* Move::_internal_mutable_toserver() {
  
  if (toserver_ == nullptr) {
    auto* p = CreateMaybeMessage<::Zee::Proto::Data::DedicateServer>(GetArenaForAllocation());
    toserver_ = p;
  }
  return toserver_;
}
inline ::Zee::Proto::Data::DedicateServer* Move::mutable_toserver() {
  ::Zee::Proto::Data::DedicateServer* _msg = _internal_mutable_toserver();
  // @@protoc_insertion_point(field_mutable:Zee.Proto.Dedicate.Move.ToServer)
  return _msg;
}
inline void Move::set_allocated_toserver(::Zee::Proto::Data::DedicateServer* toserver) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(toserver_);
  }
  if (toserver) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper<
            ::PROTOBUF_NAMESPACE_ID::MessageLite>::GetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(toserver));
    if (message_arena != submessage_arena) {
      toserver = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, toserver, submessage_arena);
    }
    
  } else {
    
  }
  toserver_ = toserver;
  // @@protoc_insertion_point(field_set_allocated:Zee.Proto.Dedicate.Move.ToServer)
}

// .Zee.Proto.Data.Position Position = 4;
inline bool Move::_internal_has_position() const {
  return this != internal_default_instance() && position_ != nullptr;
}
inline bool Move::has_position() const {
  return _internal_has_position();
}
inline const ::Zee::Proto::Data::Position& Move::_internal_position() const {
  const ::Zee::Proto::Data::Position* p = position_;
  return p != nullptr ? *p : reinterpret_cast<const ::Zee::Proto::Data::Position&>(
      ::Zee::Proto::Data::_Position_default_instance_);
}
inline const ::Zee::Proto::Data::Position& Move::position() const {
  // @@protoc_insertion_point(field_get:Zee.Proto.Dedicate.Move.Position)
  return _internal_position();
}
inline void Move::unsafe_arena_set_allocated_position(
    ::Zee::Proto::Data::Position* position) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(position_);
  }
  position_ = position;
  if (position) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:Zee.Proto.Dedicate.Move.Position)
}
inline ::Zee::Proto::Data::Position* Move::release_position() {
  
  ::Zee::Proto::Data::Position* temp = position_;
  position_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::Zee::Proto::Data::Position* Move::unsafe_arena_release_position() {
  // @@protoc_insertion_point(field_release:Zee.Proto.Dedicate.Move.Position)
  
  ::Zee::Proto::Data::Position* temp = position_;
  position_ = nullptr;
  return temp;
}
inline ::Zee::Proto::Data::Position* Move::_internal_mutable_position() {
  
  if (position_ == nullptr) {
    auto* p = CreateMaybeMessage<::Zee::Proto::Data::Position>(GetArenaForAllocation());
    position_ = p;
  }
  return position_;
}
inline ::Zee::Proto::Data::Position* Move::mutable_position() {
  ::Zee::Proto::Data::Position* _msg = _internal_mutable_position();
  // @@protoc_insertion_point(field_mutable:Zee.Proto.Dedicate.Move.Position)
  return _msg;
}
inline void Move::set_allocated_position(::Zee::Proto::Data::Position* position) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(position_);
  }
  if (position) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper<
            ::PROTOBUF_NAMESPACE_ID::MessageLite>::GetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(position));
    if (message_arena != submessage_arena) {
      position = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, position, submessage_arena);
    }
    
  } else {
    
  }
  position_ = position;
  // @@protoc_insertion_point(field_set_allocated:Zee.Proto.Dedicate.Move.Position)
}

// string UserIp = 5;
inline void Move::clear_userip() {
  userip_.ClearToEmpty();
}
inline const std::string& Move::userip() const {
  // @@protoc_insertion_point(field_get:Zee.Proto.Dedicate.Move.UserIp)
  return _internal_userip();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Move::set_userip(ArgT0&& arg0, ArgT... args) {
 
 userip_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:Zee.Proto.Dedicate.Move.UserIp)
}
inline std::string* Move::mutable_userip() {
  std::string* _s = _internal_mutable_userip();
  // @@protoc_insertion_point(field_mutable:Zee.Proto.Dedicate.Move.UserIp)
  return _s;
}
inline const std::string& Move::_internal_userip() const {
  return userip_.Get();
}
inline void Move::_internal_set_userip(const std::string& value) {
  
  userip_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* Move::_internal_mutable_userip() {
  
  return userip_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* Move::release_userip() {
  // @@protoc_insertion_point(field_release:Zee.Proto.Dedicate.Move.UserIp)
  return userip_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void Move::set_allocated_userip(std::string* userip) {
  if (userip != nullptr) {
    
  } else {
    
  }
  userip_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), userip,
      GetArenaForAllocation());
  // @@protoc_insertion_point(field_set_allocated:Zee.Proto.Dedicate.Move.UserIp)
}

// -------------------------------------------------------------------

// Leave

// .Zee.Proto.Data.Character Character = 1;
inline bool Leave::_internal_has_character() const {
  return this != internal_default_instance() && character_ != nullptr;
}
inline bool Leave::has_character() const {
  return _internal_has_character();
}
inline const ::Zee::Proto::Data::Character& Leave::_internal_character() const {
  const ::Zee::Proto::Data::Character* p = character_;
  return p != nullptr ? *p : reinterpret_cast<const ::Zee::Proto::Data::Character&>(
      ::Zee::Proto::Data::_Character_default_instance_);
}
inline const ::Zee::Proto::Data::Character& Leave::character() const {
  // @@protoc_insertion_point(field_get:Zee.Proto.Dedicate.Leave.Character)
  return _internal_character();
}
inline void Leave::unsafe_arena_set_allocated_character(
    ::Zee::Proto::Data::Character* character) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(character_);
  }
  character_ = character;
  if (character) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:Zee.Proto.Dedicate.Leave.Character)
}
inline ::Zee::Proto::Data::Character* Leave::release_character() {
  
  ::Zee::Proto::Data::Character* temp = character_;
  character_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::Zee::Proto::Data::Character* Leave::unsafe_arena_release_character() {
  // @@protoc_insertion_point(field_release:Zee.Proto.Dedicate.Leave.Character)
  
  ::Zee::Proto::Data::Character* temp = character_;
  character_ = nullptr;
  return temp;
}
inline ::Zee::Proto::Data::Character* Leave::_internal_mutable_character() {
  
  if (character_ == nullptr) {
    auto* p = CreateMaybeMessage<::Zee::Proto::Data::Character>(GetArenaForAllocation());
    character_ = p;
  }
  return character_;
}
inline ::Zee::Proto::Data::Character* Leave::mutable_character() {
  ::Zee::Proto::Data::Character* _msg = _internal_mutable_character();
  // @@protoc_insertion_point(field_mutable:Zee.Proto.Dedicate.Leave.Character)
  return _msg;
}
inline void Leave::set_allocated_character(::Zee::Proto::Data::Character* character) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(character_);
  }
  if (character) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper<
            ::PROTOBUF_NAMESPACE_ID::MessageLite>::GetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(character));
    if (message_arena != submessage_arena) {
      character = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, character, submessage_arena);
    }
    
  } else {
    
  }
  character_ = character;
  // @@protoc_insertion_point(field_set_allocated:Zee.Proto.Dedicate.Leave.Character)
}

// .Zee.Proto.Data.Position Position = 2;
inline bool Leave::_internal_has_position() const {
  return this != internal_default_instance() && position_ != nullptr;
}
inline bool Leave::has_position() const {
  return _internal_has_position();
}
inline const ::Zee::Proto::Data::Position& Leave::_internal_position() const {
  const ::Zee::Proto::Data::Position* p = position_;
  return p != nullptr ? *p : reinterpret_cast<const ::Zee::Proto::Data::Position&>(
      ::Zee::Proto::Data::_Position_default_instance_);
}
inline const ::Zee::Proto::Data::Position& Leave::position() const {
  // @@protoc_insertion_point(field_get:Zee.Proto.Dedicate.Leave.Position)
  return _internal_position();
}
inline void Leave::unsafe_arena_set_allocated_position(
    ::Zee::Proto::Data::Position* position) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(position_);
  }
  position_ = position;
  if (position) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:Zee.Proto.Dedicate.Leave.Position)
}
inline ::Zee::Proto::Data::Position* Leave::release_position() {
  
  ::Zee::Proto::Data::Position* temp = position_;
  position_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::Zee::Proto::Data::Position* Leave::unsafe_arena_release_position() {
  // @@protoc_insertion_point(field_release:Zee.Proto.Dedicate.Leave.Position)
  
  ::Zee::Proto::Data::Position* temp = position_;
  position_ = nullptr;
  return temp;
}
inline ::Zee::Proto::Data::Position* Leave::_internal_mutable_position() {
  
  if (position_ == nullptr) {
    auto* p = CreateMaybeMessage<::Zee::Proto::Data::Position>(GetArenaForAllocation());
    position_ = p;
  }
  return position_;
}
inline ::Zee::Proto::Data::Position* Leave::mutable_position() {
  ::Zee::Proto::Data::Position* _msg = _internal_mutable_position();
  // @@protoc_insertion_point(field_mutable:Zee.Proto.Dedicate.Leave.Position)
  return _msg;
}
inline void Leave::set_allocated_position(::Zee::Proto::Data::Position* position) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(position_);
  }
  if (position) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper<
            ::PROTOBUF_NAMESPACE_ID::MessageLite>::GetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(position));
    if (message_arena != submessage_arena) {
      position = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, position, submessage_arena);
    }
    
  } else {
    
  }
  position_ = position;
  // @@protoc_insertion_point(field_set_allocated:Zee.Proto.Dedicate.Leave.Position)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace Dedicate
}  // namespace Proto
}  // namespace Zee

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::Zee::Proto::Dedicate::ReturnCode> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::Zee::Proto::Dedicate::ReturnCode>() {
  return ::Zee::Proto::Dedicate::ReturnCode_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_Dedicate_2eproto
