// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Depth1/test2.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from Depth1/test2.proto</summary>
public static partial class Test2Reflection {

  #region Descriptor
  /// <summary>File descriptor for Depth1/test2.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static Test2Reflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "ChJEZXB0aDEvdGVzdDIucHJvdG8aC3Rlc3QxLnByb3RvGhlEZXB0aDEvRGVw",
          "dGgyL3Rlc3QzLnByb3RvIl8KC0RlcHRoMVRlc3QyEgkKAWEYASABKAkSJwoB",
          "cBgCIAEoCzIcLlRlbXAxLlQyLlR0NC5UdDEuVDEyLlBlcnNvbhIcCgNEVDMY",
          "AyABKAsyDy5QMS5EZXB0aDJUZXN0M2IGcHJvdG8z"));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { global::Temp1.T2.Tt4.Tt1.T12.Test1Reflection.Descriptor, global::P1.Test3Reflection.Descriptor, },
        new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::Depth1Test2), global::Depth1Test2.Parser, new[]{ "A", "P", "DT3" }, null, null, null, null)
        }));
  }
  #endregion

}
#region Messages
[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
public sealed partial class Depth1Test2 : pb::IMessage<Depth1Test2>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<Depth1Test2> _parser = new pb::MessageParser<Depth1Test2>(() => new Depth1Test2());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<Depth1Test2> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::Test2Reflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public Depth1Test2() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public Depth1Test2(Depth1Test2 other) : this() {
    a_ = other.a_;
    p_ = other.p_ != null ? other.p_.Clone() : null;
    dT3_ = other.dT3_ != null ? other.dT3_.Clone() : null;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public Depth1Test2 Clone() {
    return new Depth1Test2(this);
  }

  /// <summary>Field number for the "a" field.</summary>
  public const int AFieldNumber = 1;
  private string a_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string A {
    get { return a_; }
    set {
      a_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "p" field.</summary>
  public const int PFieldNumber = 2;
  private global::Temp1.T2.Tt4.Tt1.T12.Person p_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::Temp1.T2.Tt4.Tt1.T12.Person P {
    get { return p_; }
    set {
      p_ = value;
    }
  }

  /// <summary>Field number for the "DT3" field.</summary>
  public const int DT3FieldNumber = 3;
  private global::P1.Depth2Test3 dT3_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::P1.Depth2Test3 DT3 {
    get { return dT3_; }
    set {
      dT3_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as Depth1Test2);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(Depth1Test2 other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (A != other.A) return false;
    if (!object.Equals(P, other.P)) return false;
    if (!object.Equals(DT3, other.DT3)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (A.Length != 0) hash ^= A.GetHashCode();
    if (p_ != null) hash ^= P.GetHashCode();
    if (dT3_ != null) hash ^= DT3.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (A.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(A);
    }
    if (p_ != null) {
      output.WriteRawTag(18);
      output.WriteMessage(P);
    }
    if (dT3_ != null) {
      output.WriteRawTag(26);
      output.WriteMessage(DT3);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (A.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(A);
    }
    if (p_ != null) {
      output.WriteRawTag(18);
      output.WriteMessage(P);
    }
    if (dT3_ != null) {
      output.WriteRawTag(26);
      output.WriteMessage(DT3);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (A.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(A);
    }
    if (p_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(P);
    }
    if (dT3_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(DT3);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(Depth1Test2 other) {
    if (other == null) {
      return;
    }
    if (other.A.Length != 0) {
      A = other.A;
    }
    if (other.p_ != null) {
      if (p_ == null) {
        P = new global::Temp1.T2.Tt4.Tt1.T12.Person();
      }
      P.MergeFrom(other.P);
    }
    if (other.dT3_ != null) {
      if (dT3_ == null) {
        DT3 = new global::P1.Depth2Test3();
      }
      DT3.MergeFrom(other.DT3);
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          A = input.ReadString();
          break;
        }
        case 18: {
          if (p_ == null) {
            P = new global::Temp1.T2.Tt4.Tt1.T12.Person();
          }
          input.ReadMessage(P);
          break;
        }
        case 26: {
          if (dT3_ == null) {
            DT3 = new global::P1.Depth2Test3();
          }
          input.ReadMessage(DT3);
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 10: {
          A = input.ReadString();
          break;
        }
        case 18: {
          if (p_ == null) {
            P = new global::Temp1.T2.Tt4.Tt1.T12.Person();
          }
          input.ReadMessage(P);
          break;
        }
        case 26: {
          if (dT3_ == null) {
            DT3 = new global::P1.Depth2Test3();
          }
          input.ReadMessage(DT3);
          break;
        }
      }
    }
  }
  #endif

}

#endregion


#endregion Designer generated code
